package xyz.block.artifactswap.functionaltest.fixtures

import com.autonomousapps.kit.GradleProject
import java.io.File
import java.io.PrintWriter
import java.io.StringWriter
import java.nio.file.Path
import picocli.CommandLine
import xyz.block.artifactswap.cli.commands.BomPublishingCommand
import xyz.block.artifactswap.cli.commands.HashingCommand

/**
 * Helper class for running CLI commands in functional tests by invoking picocli directly
 * in-process.
 *
 * This allows tests to exercise the CLI workflow including hashing and BOM publishing without
 * spawning separate processes or building shadow JARs.
 */
class CliRunner(private val projectDir: File, private val mavenLocalPath: Path) {

  companion object {
    /** Creates a CliRunner for the given GradleProject. */
    fun forProject(project: GradleProject, mavenLocalPath: Path): CliRunner {
      return CliRunner(project.rootDir, mavenLocalPath)
    }
  }

  /**
   * Runs the hashing command to generate project hashes.
   *
   * @param hashingOutputFile Path to write the hashing output file
   * @return The result from the command
   */
  fun runHashing(hashingOutputFile: Path): CliResult {
    hashingOutputFile.parent?.toFile()?.mkdirs()

    return executeCommand(
      HashingCommand(),
      "--dir",
      projectDir.absolutePath,
      "--hashing-output-file",
      hashingOutputFile.toAbsolutePath().toString(),
    )
  }

  /**
   * Runs the BOM publisher command with --local flag to publish BOM to local maven repository.
   *
   * @param bomVersion The version for the BOM (typically a git commit SHA)
   * @param hashFilePath Path to the hash file generated by the hashing command
   * @return The result from the command
   */
  fun runBomPublisher(bomVersion: String, hashFilePath: Path): CliResult {
    return executeCommand(
      BomPublishingCommand(),
      "--dir",
      projectDir.absolutePath,
      "--bom-version",
      bomVersion,
      "--hash-file-location",
      hashFilePath.toAbsolutePath().toString(),
      "--local",
    )
  }

  /** Executes a CLI command in-process via picocli, capturing stdout/stderr. */
  private fun executeCommand(command: Any, vararg args: String): CliResult {
    val stringWriter = StringWriter()
    val printWriter = PrintWriter(stringWriter)

    val commandLine = CommandLine(command)
    commandLine.out = printWriter
    commandLine.err = printWriter

    val exitCode = commandLine.execute(*args)

    return CliResult(exitCode = exitCode, output = stringWriter.toString())
  }

  /**
   * Verifies that the BOM was published to the local maven repository.
   *
   * @param mavenGroup The maven group ID
   * @param bomVersion The BOM version to check
   * @return True if the BOM POM file exists
   */
  fun verifyBomPublished(mavenGroup: String, bomVersion: String): Boolean {
    val groupPath = mavenGroup.replace(".", "/")
    val bomPomPath = mavenLocalPath.resolve(groupPath).resolve("bom").resolve(bomVersion)
    return bomPomPath.toFile().exists()
  }

  /**
   * Verifies that an artifact was published to the local maven repository.
   *
   * @param mavenGroup The maven group ID
   * @param artifactId The artifact ID
   * @param version The artifact version
   * @return True if the artifact POM file exists
   */
  fun verifyArtifactPublished(mavenGroup: String, artifactId: String, version: String): Boolean {
    val groupPath = mavenGroup.replace(".", "/")
    val artifactPomPath =
      mavenLocalPath
        .resolve(groupPath)
        .resolve(artifactId)
        .resolve(version)
        .resolve("$artifactId-$version.pom")
    return artifactPomPath.toFile().exists()
  }
}

/** Result of running a CLI command. */
data class CliResult(val exitCode: Int, val output: String) {
  /** Returns true if the command succeeded (exit code 0). */
  val isSuccess: Boolean
    get() = exitCode == 0
}
